model_name: best_M_model.pt
confidance: 0.6
stream_url: rtsp://admin:123456789a@10.113.100.97:554/1
reconnection_time: 5
screen_frame_name: Texnopark_Refregirator_classification
rect_width: 1000
rect_height: 500
tcp_server_ip: "10.113.100.82"
tcp_server_port: 8001